---

name: build_docker_image

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}/:latest
